/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "storage.h"

bool_t
xdr_list (XDR *xdrs, list *objp)
{
	// register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->file.file_val, (u_int *) &objp->file.file_len, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (list), (xdrproc_t) xdr_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_t_list (XDR *xdrs, t_list *objp)
{
	// register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (list), (xdrproc_t) xdr_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listUsers (XDR *xdrs, listUsers *objp)
{
	// register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->user.user_val, (u_int *) &objp->user.user_len, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->ip.ip_val, (u_int *) &objp->ip.ip_len, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->port.port_val, (u_int *) &objp->port.port_len, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (listUsers), (xdrproc_t) xdr_listUsers))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_t_listUsers (XDR *xdrs, t_listUsers *objp)
{
	// register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (listUsers), (xdrproc_t) xdr_listUsers))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_publish_1_argument (XDR *xdrs, publish_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->user, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->desc, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_deletecontent_1_argument (XDR *xdrs, deletecontent_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->user, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_connectuser_1_argument (XDR *xdrs, connectuser_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->user, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->ip, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->port, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_check_list_content_1_argument (XDR *xdrs, check_list_content_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->user, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->userTarget, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_list_content_1_argument (XDR *xdrs, list_content_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->userTarget, 256))
		 return FALSE;
	return TRUE;
}
