/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "storage.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
registeruser_1(char *user, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, registerUser,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
unregisteruser_1(char *user, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, unregisterUser,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
publish_1(char *user, char *file, char *desc, int *clnt_res,  CLIENT *clnt)
{
	publish_1_argument arg;
	arg.user = user;
	arg.file = file;
	arg.desc = desc;
	return (clnt_call (clnt, publish, (xdrproc_t) xdr_publish_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
deletecontent_1(char *user, char *file, int *clnt_res,  CLIENT *clnt)
{
	deletecontent_1_argument arg;
	arg.user = user;
	arg.file = file;
	return (clnt_call (clnt, deleteContent, (xdrproc_t) xdr_deletecontent_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
connectuser_1(char *user, char *ip, char *port, int *clnt_res,  CLIENT *clnt)
{
	connectuser_1_argument arg;
	arg.user = user;
	arg.ip = ip;
	arg.port = port;
	return (clnt_call (clnt, connectUser, (xdrproc_t) xdr_connectuser_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
disconnectuser_1(char *user, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, disconnectUser,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
check_list_users_1(char *user, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, check_list_users,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
list_users_1(int n, t_listUsers *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, list_users,
		(xdrproc_t) xdr_int, (caddr_t) &n,
		(xdrproc_t) xdr_t_listUsers, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
check_list_content_1(char *user, char *userTarget, int *clnt_res,  CLIENT *clnt)
{
	check_list_content_1_argument arg;
	arg.user = user;
	arg.userTarget = userTarget;
	return (clnt_call (clnt, check_list_content, (xdrproc_t) xdr_check_list_content_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
list_content_1(int n, char *userTarget, t_list *clnt_res,  CLIENT *clnt)
{
	list_content_1_argument arg;
	arg.n = n;
	arg.userTarget = userTarget;
	return (clnt_call (clnt, list_content, (xdrproc_t) xdr_list_content_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_t_list, (caddr_t) clnt_res,
		TIMEOUT));
}
