/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "storage.h"


void
storage_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	char *registeruser_1_user;
	enum clnt_stat retval_2;
	int result_2;
	char *unregisteruser_1_user;
	enum clnt_stat retval_3;
	int result_3;
	char *publish_1_user;
	char *publish_1_file;
	char *publish_1_desc;
	enum clnt_stat retval_4;
	int result_4;
	char *deletecontent_1_user;
	char *deletecontent_1_file;
	enum clnt_stat retval_5;
	int result_5;
	char *connectuser_1_user;
	char *connectuser_1_ip;
	char *connectuser_1_port;
	enum clnt_stat retval_6;
	int result_6;
	char *disconnectuser_1_user;
	enum clnt_stat retval_7;
	int result_7;
	char *check_list_users_1_user;
	enum clnt_stat retval_8;
	t_listUsers result_8;
	enum clnt_stat retval_9;
	int result_9;
	char *check_list_content_1_user;
	char *check_list_content_1_userTarget;
	enum clnt_stat retval_10;
	t_list result_10;
	char *list_content_1_userTarget;

#ifndef	DEBUG
	clnt = clnt_create (host, STORAGE, STORAGEVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = registeruser_1(registeruser_1_user, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = unregisteruser_1(unregisteruser_1_user, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = publish_1(publish_1_user, publish_1_file, publish_1_desc, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = deletecontent_1(deletecontent_1_user, deletecontent_1_file, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = connectuser_1(connectuser_1_user, connectuser_1_ip, connectuser_1_port, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = disconnectuser_1(disconnectuser_1_user, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_7 = check_list_users_1(check_list_users_1_user, &result_7, clnt);
	if (retval_7 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_8 = listconnectedusers_1(&result_8, clnt);
	if (retval_8 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_9 = check_list_content_1(check_list_content_1_user, check_list_content_1_userTarget, &result_9, clnt);
	if (retval_9 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_10 = list_content_1(list_content_1_userTarget, &result_10, clnt);
	if (retval_10 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	storage_1 (host);
exit (0);
}
