/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "storage.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_registeruser_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (registeruser_1_svc(*argp, result, rqstp));
}

int
_unregisteruser_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (unregisteruser_1_svc(*argp, result, rqstp));
}

int
_publish_1 (publish_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (publish_1_svc(argp->user, argp->file, argp->desc, result, rqstp));
}

int
_deletecontent_1 (deletecontent_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (deletecontent_1_svc(argp->user, argp->file, result, rqstp));
}

int
_connectuser_1 (connectuser_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (connectuser_1_svc(argp->user, argp->ip, argp->port, result, rqstp));
}

int
_disconnectuser_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (disconnectuser_1_svc(*argp, result, rqstp));
}

int
_check_list_users_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (check_list_users_1_svc(*argp, result, rqstp));
}

int
_list_users_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (list_users_1_svc(*argp, result, rqstp));
}

int
_check_list_content_1 (check_list_content_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (check_list_content_1_svc(argp->user, argp->userTarget, result, rqstp));
}

int
_list_content_1 (list_content_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (list_content_1_svc(argp->n, argp->userTarget, result, rqstp));
}

static void
storage_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *registeruser_1_arg;
		char *unregisteruser_1_arg;
		publish_1_argument publish_1_arg;
		deletecontent_1_argument deletecontent_1_arg;
		connectuser_1_argument connectuser_1_arg;
		char *disconnectuser_1_arg;
		char *check_list_users_1_arg;
		int list_users_1_arg;
		check_list_content_1_argument check_list_content_1_arg;
		list_content_1_argument list_content_1_arg;
	} argument;
	union {
		int registeruser_1_res;
		int unregisteruser_1_res;
		int publish_1_res;
		int deletecontent_1_res;
		int connectuser_1_res;
		int disconnectuser_1_res;
		int check_list_users_1_res;
		t_listUsers list_users_1_res;
		int check_list_content_1_res;
		t_list list_content_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case registerUser:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_registeruser_1;
		break;

	case unregisterUser:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_unregisteruser_1;
		break;

	case publish:
		_xdr_argument = (xdrproc_t) xdr_publish_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_publish_1;
		break;

	case deleteContent:
		_xdr_argument = (xdrproc_t) xdr_deletecontent_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_deletecontent_1;
		break;

	case connectUser:
		_xdr_argument = (xdrproc_t) xdr_connectuser_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_connectuser_1;
		break;

	case disconnectUser:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_disconnectuser_1;
		break;

	case check_list_users:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_check_list_users_1;
		break;

	case list_users:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_t_listUsers;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_list_users_1;
		break;

	case check_list_content:
		_xdr_argument = (xdrproc_t) xdr_check_list_content_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_check_list_content_1;
		break;

	case list_content:
		_xdr_argument = (xdrproc_t) xdr_list_content_1_argument;
		_xdr_result = (xdrproc_t) xdr_t_list;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_list_content_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!storage_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (STORAGE, STORAGEVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, STORAGE, STORAGEVER, storage_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (STORAGE, STORAGEVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, STORAGE, STORAGEVER, storage_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (STORAGE, STORAGEVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
